### ISSUE TITLE
Update data types to reflect current documentation

### ISSUE THREAD

**Issue by mattgenious** [deptno/gtag#3]
the data types need to be updated to reflect the shapes defined here https://developers.google.com/gtagjs/reference/ga4-events

**Comment by mattgenious** [comment]
work on this  issue is started at #2

**Comment by deptno** [comment]
https://github.com/deptno/gtag/packages/379716?version=0.2.1

**Comment by mattgenious** [comment]
Hey @deptno the work was not finished, but I did not have time to finish it.
The data types are quite different from the documentation still.

**Comment by deptno** [comment]
ok. I will work on it later.
